### ISSUE TITLE
Esp32 porting

### ISSUE THREAD

**Issue by Testato** [5N44P/unisolder-notes#1]
I propose to start to work on an Wiring porting for Esp32 mcu, with Ota+wifi+bt future expansion.

**Comment by 5N44P** [comment]
I don't know if the ESP can hanlde all the fpu computation (required for the pid), the original project uses a PIC32MX. Moreover there are no source file released at the moment, and the author doesn't plan to release them. 
Btw this repo is just intended to be a bom and assembly guide, we should reefer to the original topic on Dangerousprototypes' forum... 


PS we have still some work to do with [ADB-3020-CDV](https://github.com/Testato/ADB-3020-CDV)

**Comment by Testato** [comment]
No open source project ?
Xxxxccccccbbnkllgfsshjk
Please add this info and link to the project on the first page of this Readme.

+1 for the ADB project

**Comment by 5N44P** [comment]
Schematics, gerbers and all the informations are released, but the board was designed in altium designer, expensive proprietary software... So anyway we couldn't do anything with the altium designer's files.

**Comment by 5N44P** [comment]
Also the firmware is open. 
The only thing are the altium designer's files...

**Comment by Testato** [comment]
Ok, so it is completely opensource and in teory is is possible a porting of the board files and firmware to for example eagle+wiring
