### ISSUE TITLE
Merging back some forks into main

### ISSUE THREAD

**Issue by 5N44P** [5N44P/unisolder-notes#10]
Hi everyone, 
I see that some of you are continuing the work in some forks, doing a great job of expanding the documentation.
In particular:
- @lauer2356's [fork](https://github.com/lauer2356/unisolder-notes)
- @rsre's [fork](https://github.com/rsre/unisolder-notes)

What do you think about merging all this information in the main repo, adding a credits/contributors section?

**Comment by 5N44P** [comment]
See also #8

**Comment by rsre** [comment]
My fork only has a few typos fixed, I haven't added nothing special. Feel free to merge it into your repo.

**Comment by 5N44P** [comment]
Everything merged! Thanks
