### ISSUE TITLE
Wiring questions

### ISSUE THREAD

**Issue by curieos** [5N44P/unisolder-notes#14]
I figured out which pins were which on the power supply board, but now I need to figure out where they plug into the control board. I can't find anything about how to hook this up, pin 1 isn't labelled in any way.

**Comment by nicola-d** [comment]
From http://dangerousprototypes.com/forum/index.php?topic=7218.msg66364#msg66364
![PUZZ1026b](https://user-images.githubusercontent.com/35398695/73494895-be5b0880-43b5-11ea-8cb3-2efaa208af99.jpg)

**Comment by curieos** [comment]
Thanks for showing me this!
