### ISSUE TITLE
Board won't program

### ISSUE THREAD

**Issue by curieos** [5N44P/unisolder-notes#15]
I've tried multiple things, but the board won't program. I've powered it via the power supply board and everything. The programmer always errors out, saying it cant detect the appropriate voltage level. Any ideas on troubleshooting? I can upload pics of both boards tomorrow, but I'm pretty sure all the components are oriented correctly.

**Comment by nicola-d** [comment]
I had some troubles as well when I first attempted to program the microcontroller. Now, I mostly forgot what the problem was... Just a few notes:

Remember to connect Pickit to UniS board, 'arrow' pin on Pickit should connect to programming pin UniS board - it is the only one with SQUARE pad, others are round pads. 5 pins on UniS board used out 6 pins on Pickit, pin 6 is not used.

Start MPLab IPE (not IDE app within the package, which is for development purposes).

You can find some more info on the forum: http://dangerousprototypes.com/forum/index.php?topic=7218.msg68299#msg68299

Hope this helps...

**Comment by curieos** [comment]
I seem to have a short on my board somewhere on the 3.3v line. I'm not sure where though. I do know that I accidentally flipped the -.6v and 3.3v rails at one point, could I have possibly damaged something?

**Comment by nicola-d** [comment]
U13 (MCP6V27-E/SN) is connected to the 3.3v and -0.6v rails (the others are connected to 3.3v and GND). Flipping those lines can have burned the chip and made an internal short circuit. Try to desolder U13 and check if the short is still present.

**Comment by nicola-d** [comment]
Also U18 is powered by 3.3 and -0.6v.

**Comment by curieos** [comment]
I tried both, one at a time, both seem fine unfortunately. I did find some extra solder under one of them that might've been shorting other things, so I've been checking all the others, but I haven't found the culprit yet.

**Comment by nicola-d** [comment]
Also U16 is connected to -0.6v

**Comment by nicola-d** [comment]
By the way, all these chips are not needed to program the PIC microcontroller.

**Comment by curieos** [comment]
I figured. Unfortunately nothing I've tried has fixed things.

**Comment by nicola-d** [comment]
You can locate the short(s) looking for points where the board heats up. For example touching the ICs still in place. But don't leave the board powered up for too long. If you have access to a thermal camera things are going to be a lot easier...

**Comment by curieos** [comment]
I tried hooking the board up to an adjustable benchtop PSU set to 3.3v and 5 amps. It dropped down to .5v at 5 amps when I hooked it up, and I didn't feel anything getting warm. It's almost like the board itself is dead shorted?

**Comment by nicola-d** [comment]
Well, 5 amps is way too much (I don't remember well but the front board draws something like 200mA). Are you sure there are no solder bridges somewhere? Examine thoroughly the each solder joint under a magnifying glass

**Comment by curieos** [comment]
I've looked pretty extensively at the board for solder bridges. The only ones I've found were under U13 to C24 and under C62. To double check my sanity, I just pulled all of the non-passive components to make sure nothing was hiding underneath.

**Comment by nicola-d** [comment]
Then, excluding a solder bridge, when the board is powered up you should sense a component become hot (and probably start to smoke) since is drawing 5 amps...

**Comment by nicola-d** [comment]
If you wish, you can post some hi-res photos of the board. I'll try to help locating the troubles...

**Comment by Tig3rch3n** [comment]
Hey ho,
I finished my Unisolder a few months ago and had some Flashing troubles as well but before I tried flashing I did some measurements first.

Some where on the forum someone posted a list of test points with the corresponding voltages.

Speaking about power consumption...
The PSU part without the Front bit pulled about 100-110mAh? 

All connected without the Handle it used 170-185mAh

Like Nicola said, publish some High res Images...

And try the test points, first just the PSU and than connect everything and do some additional probing :p

**Comment by curieos** [comment]
Here's a drive folder with images of my board.
https://drive.google.com/open?id=1Uwd7klpFu7USx8ZZ3M75HeDvMTSG1hE5

**Comment by nicola-d** [comment]
Can you add another picture of U16 and surrounding area? That photo is a bit out of focus

**Comment by curieos** [comment]
Done

**Comment by nicola-d** [comment]
From the photos, it looks like two pins (bottom left and central) of U11 are bridged.

**Comment by curieos** [comment]
Nice catch, no luck with the short though.

**Comment by curieos** [comment]
Btw, just measured and it's a 0 ohm short

**Comment by curieos** [comment]
I'm starting to think maybe one of the vias got some solder paste in it and maybe that's where the short is

**Comment by nicola-d** [comment]
If you have a couple of sharp multimeter probes I would test each adjacent pin of U16 for continuity. The pitch is very small and it is easy to overlook a bridge.

**Comment by nicola-d** [comment]
Also check C49 and C40. Not sure but there seems to be some bridging... They are connected to 3.3v and GND.

**Comment by curieos** [comment]
Doesn't look like it, I was real careful with those two. They like to touch

**Comment by curieos** [comment]
I found the short and got the board programmed. Turns out there was a short under C35

**Comment by curieos** [comment]
New problem, LCD isn't working.

**Comment by curieos** [comment]
Turns out I just flashed the incorrect bootloader/firmware. All is good! Thanks for all the help!
