### ISSUE TITLE
Can not open file :bom_unisolder.xlsx

### ISSUE THREAD

**Issue by bjornsundklakk** [5N44P/unisolder-notes#5]

**Comment by Tig3rch3n** [comment]
The file is definitely okay... I just started yesterday a order list for mouser part numbers out of this list. 
I just checked it again with my phone just now and it works fine. 

Try deleting the folder and re downloading it... 
Or just download the one file with your browser

**Comment by 5N44P** [comment]
@Tig3rch3n thank you for the confirm. Btw would you make a pr with the mouser bom?

**Comment by Tig3rch3n** [comment]
@5N44P jup... I hope to get a "mouser only" list if possible... Minus the LCD :p

**Comment by bjornsundklakk** [comment]
I was not my intention to devalue your bom. I just ha a problem to open the
bom from your notes site when i downloaded it directly. I got som strange
red error popup message. Later on i downloaded the zipfile from the git and
then I had no problem open it in libre office calc. Great jo you do, making
this unisolder notes site. It will help me a lot as i`m studying this
unisolder blog and I`m planning to build the unisolder 5.2.
Some critics i have to give you afterall as i`m writing:

1. It would have been nice if the links in your bom  where active, then we
you could just Ctrl click and the link will open in the browser.

2. It would have been even nicer if your links in the tme site and others
opened up in English.

In this way your bom will help me and i`m shure others alot more.

puzzle have a realy nice bom on side 123 "UniSolder_BOM_edit_10.xls"

Regard
Bjørn Sundklakk

Den ons. 14. nov. 2018 kl. 23:49 skrev Tig3rch3n <notifications@github.com>:

**Comment by 5N44P** [comment]
@bjornsundklakk thank you for your feedback, i appreciate. 
At the present time i have no time to implement your advices into the BOM, but i can review and accept pull requests, if you want to help!
